version: '3'
services:
  frontend:
    build: ./react-application-dev/frontend
    container_name: restaurant-app
    volumes:
      - ./react-application-dev/frontend:/app
    ports:
      - 8080:8080
    depends_on:
      - backend

  backend:
    build: ./react-application-dev/backend
    container_name: backend
    volumes:
      - ./react-application-dev/backend:/app
    ports:
      - 8081:8081
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
       MYSQL_ROOT_PASSWORD: demo
       MYSQL_DATABASE: db_restaurant
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: demo
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  datadog_sidecar:
      build: ./datadog-sidecar/
      depends_on:
        - frontend
      environment:
        - DD_API_KEY=${datadog_api_key}
        - DD_APM_NON_LOCAL_TRAFFIC=true
        - DD_APM_ANALYZED_SPANS="browser,http,resource"
        - DD_APM_SERVICE_NAME="my-react-app"
        - DD_APM_DD_TRACE_ID_HEADERS="x-datadog-trace-id"
        - DD_PROCESS_AGENT_ENABLED=true
        - DD_LOGS_INJECTION=true
        - DD_TRACE_ANALYTICS_ENABLED=true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      networks:
        - default
volumes:
  db-data: